// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma CLI (migrate, studio, db pull, ...) uses the direct/unpooled Neon connection —
  // the app itself connects through the pooled DATABASE_URL via the Neon driver adapter
  // (see src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
